#pragma once

#include <windef.h>

#define MAKEINTRESOURCEW(x) ((LPCWSTR)x)

#define RT_ACCELERATORW  MAKEINTRESOURCEW(9)
#define RT_ANICURSORW    MAKEINTRESOURCEW(21)
#define RT_ANIICONW      MAKEINTRESOURCEW(22)
#define RT_BITMAPW       MAKEINTRESOURCEW(2)
#define RT_CURSORW       MAKEINTRESOURCEW(1)
#define RT_DIALOGW       MAKEINTRESOURCEW(5)
#define RT_DLGINCLUDEW   MAKEINTRESOURCEW(17)
#define RT_FONTW         MAKEINTRESOURCEW(8)
#define RT_FONTDIRW      MAKEINTRESOURCEW(7)
#define RT_HTMLW         MAKEINTRESOURCEW(23)
#define RT_ICONW         MAKEINTRESOURCEW(3)
#define RT_MANIFESTW     MAKEINTRESOURCEW(24)
#define RT_MENUW         MAKEINTRESOURCEW(4)
#define RT_MESSAGETABLEW MAKEINTRESOURCEW(11)
#define RT_PLUGPLAYW     MAKEINTRESOURCEW(19)
#define RT_RCDATAW       MAKEINTRESOURCEW(10)
#define RT_STRINGW       MAKEINTRESOURCEW(6)
#define RT_VERSIONW      MAKEINTRESOURCEW(16)
#define RT_VXDW          MAKEINTRESOURCEW(20)

#define RT_GROUP_CURSORW MAKEINTRESOURCEW((ULONG_PTR)RT_CURSORW + 11)
#define RT_GROUP_ICONW   MAKEINTRESOURCEW((ULONG_PTR)RT_ICONW + 11)

extern "C" {
  HMODULE WINAPI LoadLibraryExW(LPCWSTR lpLibFileName, HANDLE hFile, DWORD dwFlags);
  FARPROC WINAPI GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
  DWORD WINAPI GetModuleFileNameW(HMODULE hModule, LPWSTR lpFilename, DWORD nSize);
  HMODULE WINAPI GetModuleHandleW(LPCWSTR lpModuleName);
  HMODULE WINAPI GetModuleHandleA(LPCSTR lpModuleName);
  HRSRC WINAPI FindResourceExW(HMODULE hModule, LPCWSTR lpType, LPCWSTR lpName, WORD wLanguage);
};

