#pragma once

#include <windef.h>

struct PROC_THREAD_ATTRIBUTE_ENTRY {
  ULONG_PTR Attribute;
  SIZE_T cbSize;
  PVOID lpValue;
};

struct PROC_THREAD_ATTRIBUTE_LIST {
  DWORD dwFlags;
  ULONG Size;
  ULONG Count;
  ULONG Reserved;
  PULONG Unknown;
  PROC_THREAD_ATTRIBUTE_ENTRY Entries[1];
};

typedef PROC_THREAD_ATTRIBUTE_ENTRY* LPPROC_THREAD_ATTRIBUTE_ENTRY;

typedef PROC_THREAD_ATTRIBUTE_LIST* LPPROC_THREAD_ATTRIBUTE_LIST;
