#pragma once

#include <windef.h>

#define BASE_SEARCH_PATH_ENABLE_SAFE_SEARCHMODE  0x00000001
#define BASE_SEARCH_PATH_DISABLE_SAFE_SEARCHMODE 0x00010000
#define BASE_SEARCH_PATH_PERMANENT               0x00008000

typedef DWORD (*LPTHREAD_START_ROUTINE)(LPVOID);
typedef void (*PFIBER_START_ROUTINE)(LPVOID);

typedef PFIBER_START_ROUTINE LPFIBER_START_ROUTINE;

extern "C" {
  PVOID WINAPI EncodePointer(PVOID Ptr);
  BOOL WINAPI SetSearchPathMode(DWORD Flags);
};

