#pragma once

#include <windef.h>

#define INTERNET_DEFAULT_FTP_PORT    21
#define INTERNET_DEFAULT_GOPHER_PORT 70
#define INTERNET_DEFAULT_HTTP_PORT   80
#define INTERNET_DEFAULT_HTTPS_PORT  443
#define INTERNET_DEFAULT_SOCKS_PORT  1080
#define INTERNET_INVALID_PORT_NUMBER 0

typedef LPVOID HINTERNET;
typedef WORD   INTERNET_PORT;

typedef INTERNET_PORT* LPINTERNET_PORT;
